### ISSUE TITLE
Some question about outdoor rendering results

### ISSUE THREAD

**Issue by eliliu2233** [OpenGVLab/PonderV2#1]
Thanks for your exciting work! I'm learning outdoor reconstruction recently and I'm really interested in your rendering results in Fig.9. Could you please tell me what is the real size of an outdoor scene in your paper? It is really surprising to achieve such accurate and detailed rendering results only with the resolution of 180*180*5 in driving scenes.

**Comment by Nightmare-n** [comment]
Thanks for your interest! The rendered results were achieved by the resolution of 128\*128\*21 in our early experiments, where we found that a larger height dimension was essential for better rendering results.
![image](https://github.com/OpenGVLab/PonderV2/assets/47742823/19e49b61-d4d0-43bc-a44d-148442d094e7)

**Comment by eliliu2233** [comment]
Thanks for your detailed reply! It seems that the resolution of the depth images is larger than 1600*900 in the paper? Second, my intuition tells me that it may be easier to cause the result in the left figure while the grid resolution is smaller than lidar? That's an interesting finding.

**Comment by eliliu2233** [comment]
> Thanks for your interest! The rendered results were achieved by the resolution of 128*128*21 in our early experiments, where we found that a larger height dimension was essential for better rendering results. ![image](https://user-images.githubusercontent.com/47742823/278002540-19e49b61-d4d0-43bc-a44d-148442d094e7.png)
Thanks for your detailed reply! It seems that the resolution of the depth images is larger than 1600*900 in the paper? Second, my intuition tells me that it may be easier to cause the result in the left figure while the grid resolution is smaller than lidar? That's an interesting finding.

**Comment by eliliu2233** [comment]
> Thanks for your interest! The rendered results were achieved by the resolution of 128*128*21 in our early experiments, where we found that a larger height dimension was essential for better rendering results. ![image](https://user-images.githubusercontent.com/47742823/278002540-19e49b61-d4d0-43bc-a44d-148442d094e7.png)

Thanks for your detailed reply! It seems that the resolution of the depth images is larger than 1600*900 in the paper? Second, my intuition tells me that it may be easier to cause the result in the left figure while the grid resolution is smaller than lidar? That's an interesting finding.

**Comment by Nightmare-n** [comment]
Hi, the resolution of the depth image is the same as 1600 * 900 in the paper (the 2560 * 1318 pixel in the figure may be caused by plt.figure(figsize=(xx,xx))).

**Comment by eliliu2233** [comment]
> Hi, the resolution of the depth image is the same as 1600 * 900 in the paper (the 2560 * 1318 pixel in the figure may be caused by plt.figure(figsize=(xx,xx))).

OK. Thanks for your patient explanation.
