### ISSUE TITLE
Feature extraction for point clouds

### ISSUE THREAD

**Issue by YunzeMan** [OpenGVLab/PonderV2#12]
Hi, thanks for your great work. I am trying to use your PonderV2 as a frozen feature extractor for new 3D point clouds, like how people use CLIP/DINOv2 for images. 

Could you share some simple scripts or ideas about how we can achieve this with your codebase? This can be very helpful.

**Comment by HaoyiZhu** [comment]
Hi, thanks for your interest! 

You can refer to [this function](https://github.com/OpenGVLab/PonderV2/blob/main/ponder/models/ponder/ponder_indoor_base.py#L695) in Ponder model. It will return a `sparse_backbone_feat` tensor in the data dict. See [here](https://github.com/OpenGVLab/PonderV2/blob/main/ponder/models/ponder/ponder_indoor_base.py#L174C20-L174C40).

Alternatively, you can also refer to our downstream finetuning codes, where we [load the backbone's weights](https://github.com/OpenGVLab/PonderV2/blob/main/ponder/engines/hooks/misc.py#L238) to the [SparseUNet](https://github.com/OpenGVLab/PonderV2/blob/main/ponder/models/sparse_unet/spconv_unet_v1m3_pdnorm.py#L427).
