### ISSUE TITLE
Visualize Code

### ISSUE THREAD

**Issue by yotofu** [OpenGVLab/PonderV2#14]
First, Great Job! But I check the code, no visualization code for segment, any plan to release the related code ?

**Comment by HaoyiZhu** [comment]
Hi, what do you mean by "visualization code for segment"? Do you want something like visualizing each points' class label?
'

**Comment by yotofu** [comment]
> Hi, what do you mean by "visualization code for segment"? Do you want something like visualizing each points' class label? '

yes, it is easy to check the performance

**Comment by HaoyiZhu** [comment]
We have not supported this function yet. You can directly check the training loss and validation mIoU, acc, etc. We print them on each step. Also, all the metrics are saved using tensorboard.
