### ISSUE TITLE
Readme for Instance Segmentation

### ISSUE THREAD

**Issue by yotofu** [OpenGVLab/PonderV2#15]
Can you add an introduction on how to perform instance segmentation to the README? There is only introduction about semantic segmentation, I tried instance segmentation but failed, thanks

**Comment by HaoyiZhu** [comment]
Hi, have you run these instructions?
![image](https://github.com/OpenGVLab/PonderV2/assets/63538191/dd88c8c1-5732-4287-8610-c81be339f805)

**Comment by yotofu** [comment]
Yes, I followed the instruction provide above, and run " python tools/test.py --config-file configs/scannet/insseg-ppt-v1m1-0-pointgroup-spunet-ft.py --options save_path=exp/scannet/insseg-ppt-v1m1-0-pointgroup-spunet-ft weight=exp/scannet/insseg-ppt-v1m1-0-pointgroup-spunet-ft/model/model_best.pth", and  I got error below 
![image](https://github.com/OpenGVLab/PonderV2/assets/24996527/e0a3754f-15a3-419d-b740-acbf604b80dc)

**Comment by HaoyiZhu** [comment]
Hi, could you try our bash script, for example: `sh scripts/train.sh -g 4 -d scannet -c insseg-ppt-v1m1-0-pointgroup-spunet-ft -n insseg-pointgroup-v1m1-0-spunet-ft -w ${PATH/TO/CHECKPOINT}` ?

**Comment by yotofu** [comment]
![image](https://github.com/OpenGVLab/PonderV2/assets/24996527/f1859679-1aea-4c36-b1fb-2d317e6e34a4)
It's normal, I think better add more introduction about how to run instance segmentation testing below this section of text
![image](https://github.com/OpenGVLab/PonderV2/assets/24996527/33b03571-e011-4877-b6ab-f5a9f8decaf0)

**Comment by HaoyiZhu** [comment]
Sounds good!

**Comment by HaoyiZhu** [comment]
I have added the instance segmentation instructions to the funetuning section.

**Comment by yotofu** [comment]
> Yes, I followed the instruction provide above, and run " python tools/test.py --config-file configs/scannet/insseg-ppt-v1m1-0-pointgroup-spunet-ft.py --options save_path=exp/scannet/insseg-ppt-v1m1-0-pointgroup-spunet-ft weight=exp/scannet/insseg-ppt-v1m1-0-pointgroup-spunet-ft/model/model_best.pth", and I got error below ![image](https://private-user-images.githubusercontent.com/24996527/322343900-e0a3754f-15a3-419d-b740-acbf604b80dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNDkwMTYsIm5iZiI6MTcxMzI0ODcxNiwicGF0aCI6Ii8yNDk5NjUyNy8zMjIzNDM5MDAtZTBhMzc1NGYtMTVhMy00MTlkLWI3NDAtYWNiZjYwNGI4MGRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDA2MjUxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiZjE0NDc2OGNhOThiNGJmZGFhNWQxOTFjMjUwZmIxZDdhMjdjOTZhY2ZmYzViZWNiM2ZhMGFmYjJhZjk4ODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-rkaBVFjUo2uTKKBjOnywJ5YhZPi09iu_OiQEdJjZtI)

I Found the cause of this problem, first you have not config the test for instance here 
![image](https://github.com/OpenGVLab/PonderV2/assets/24996527/e85cb451-cf0a-4d70-ac8e-b9e04d010583)
second, you only implemented the SemSegTester, but no InstanceSegTester.   
![image](https://github.com/OpenGVLab/PonderV2/assets/24996527/9d364732-517d-45ca-85de-28e2561f96d9)
By the way, no tester for Reconstruction, So many work need to do ^-^

**Comment by HaoyiZhu** [comment]
Yeah, we actually have not implemented the tester for instance segmentation. I think validation results are enough. Test is for submitting to official benchmark. You can simply delete the test dataset and use the validation results :)
