### ISSUE TITLE
Question about experiment folder created by training script.

### ISSUE THREAD

**Issue by GhaitsaDina** [OpenGVLab/PonderV2#16]
Hello, thank you for your great work! I have collection of point cloud data that I want to test using your pre-trained model checkpoint. Can I use them without training the S3DIS dataset?

I'm a bit confused because from reading the testing script, there's an experiment folder that I couldn't fine anywhere except making it by training S3DIS myself. How can I test my own data without training the whole S3DIS dataset first?
![image](https://github.com/OpenGVLab/PonderV2/assets/78811552/a69a0b5f-9af9-447c-bd3b-16dcab5a76ec)

Your guidance is very much needed, thank you so much.

**Comment by HaoyiZhu** [comment]
Hi, thanks for your interest! To test on you own dataset, you can directly refer to [tools/test.py](https://github.com/OpenGVLab/PonderV2/blob/main/tools/test.py), which is just called by [scripts/test.sh](https://github.com/OpenGVLab/PonderV2/blob/main/scripts/test.sh) (see the last few lines):
```bash
$PYTHON -u tools/$TEST_CODE \
  --config-file "$CONFIG_DIR" \
  --num-gpus "$GPU" \
  --options save_path="$EXP_DIR" weight="${MODEL_DIR}"/"${WEIGHT}".pth
  ```

Also, you should write your own config, dataset loader and tester of your task. You can refer to our examples such as [ScanNet test config](https://github.com/OpenGVLab/PonderV2/blob/main/configs/scannet/semseg-spunet-v1m1-0-base.py#L131), [ScanNet test data loading](https://github.com/OpenGVLab/PonderV2/blob/main/ponder/datasets/scannet.py#L142-L170) and [semantic segmentation tester](https://github.com/OpenGVLab/PonderV2/blob/main/ponder/engines/test.py#L116).

As you can see in our [SemSegTester](https://github.com/OpenGVLab/PonderV2/blob/main/ponder/engines/test.py#L116), the basic logic is to 1) [build and load model](https://github.com/OpenGVLab/PonderV2/blob/main/ponder/engines/test.py#L59) 2) [build dataloader](https://github.com/OpenGVLab/PonderV2/blob/main/ponder/engines/test.py#L90) 3) [loop over dataloader](https://github.com/OpenGVLab/PonderV2/blob/main/ponder/engines/test.py#L161) and [get model predictions](https://github.com/OpenGVLab/PonderV2/blob/main/ponder/engines/test.py#L176-L206) 4) [compute metrics and post-processing](https://github.com/OpenGVLab/PonderV2/blob/main/ponder/engines/test.py#L212-L332)

**Comment by HaoyiZhu** [comment]
Further instructions can be found [here](https://github.com/OpenGVLab/PonderV2/blob/main/docs/getting_started.md#testing)
