### ISSUE TITLE
Estimated release date

### ISSUE THREAD

**Issue by JayKarhade** [OpenGVLab/PonderV2#2]
Hi,
Super interesting work. May I know a tentative release date?

Thank you!

**Comment by Nightmare-n** [comment]
Hi, thanks for your interest! We will release the code this month.

**Comment by HaoyiZhu** [comment]
Hi, we have released initial codes! We are still working on refactoring the whole codes and writing instructions on installation and usage. It may take some time because I am preparing for my final exam :)

**Comment by Nightmare-n** [comment]
Hi, the code for outdoor has been released at [here](https://github.com/Nightmare-n/UniPAD).

**Comment by HaoyiZhu** [comment]
Hi, we have released initial codes! You can now browse our pipeline and models @JayKarhade. We are still working on refactoring the whole codes and writing instructions on installation and usage. You can also now check the outdoor codes (the UniPAD part) in @Nightmare-n 's repo.
