### ISSUE TITLE
Visualization of RGB&Depth images

### ISSUE THREAD

**Issue by BoynextDoor114514** [OpenGVLab/PonderV2#20]
Hi, thanks for this great work. I've try to run this project with NuScenes.
I wanna know how to get rendered RGB&D-images as you've shown in your paper, could you please give me some advice?

**Comment by HaoyiZhu** [comment]
Since the issue has been replied to in [UniPAD](https://github.com/Nightmare-n/UniPAD/issues/20), I decide to close it,
