### ISSUE TITLE
Inquiry about the preprocess of ScanNet

### ISSUE THREAD

**Issue by RayYoh** [OpenGVLab/PonderV2#25]
Hi Haoyi @HaoyiZhu,

Thanks for your great work. I am confused about the preprocess of ScanNet. After extracting the posed images, I found that every scene has 5000+ images, which is not friendly for the harddisk memory; however, during the training, just 5 images are needed. I also see that MMDetection3D recommends a parameter to control the sampled image numbers (maybe 300). Does this process influence the results? Have you referred to any other works to preprocess the data?

Additionally, how to generate the file `skip.lst`.

Best

**Comment by HaoyiZhu** [comment]
Hi, thanks for the question. If you have a limited disk quota, you could try to save images every 10 or 20 frames, since the continuous frames mostly look very similar. Although we only use 5 images per batch during training, they are randomly selected from all frames. Therefore, it might result in a slight difference in the case of reproduction, but I think it is okay and has little influence on the downstream results. Our preprocessing borrows from official [ScanNet](https://github.com/ScanNet/ScanNet/blob/master/SensReader/python/reader.py) where `frame_skip` is set to 1 by default.

To generate `skip.lst`, you could refer to [this issue](https://github.com/OpenGVLab/PonderV2/issues/11).

.

**Comment by RayYoh** [comment]
Thanks for your reply. By the way, may I ask how can I reproduce the results of this config:
![image](https://github.com/user-attachments/assets/b316b17b-857c-448d-ab72-e179f0dd69b7)

Just running this config file directly: [here](https://github.com/OpenGVLab/PonderV2/blob/main/configs/scannet/semseg-spunet-v1m1-0-base.py)?

**Comment by HaoyiZhu** [comment]
Actually, I am not quite sure about it. The number is directly copied from previous works like PPT. Maybe you could ask Xiaoyang. I guess if you directly run the config, you might get a higher result since Xiaoyang has added a lot of training tricks I think.

**Comment by RayYoh** [comment]
Actually, I get a very low performance even after 20+ epochs. However, using the same pipeline, PTv3 works well.
Yeah, I have sent an email to Xiaoyang but has not get response.

Additionaly, I tried to run this config [here](https://github.com/OpenGVLab/PonderV2/blob/main/configs/scannet/pretrain-ponder-spunet-v1m1-0-base.py) which use ScanNet solely. The problem I encounter is the grid index exceeds the shape of feat a lot resulting in all zero feats.
![image](https://github.com/user-attachments/assets/7095e9a0-9b05-4531-910b-d30052c8f1c4)
I am wondering have you ever encountered this problem? And is it possible to share the checkpoint or log file of this config? Thanks a lot.

**Comment by HaoyiZhu** [comment]
I have not noticed this before. What's the shape of feat_grid? How does it compare to using [this config](https://github.com/OpenGVLab/PonderV2/blob/main/configs/scannet/pretrain-ponder-ppt-v1m1-0-sc-s3-st-spunet.py)?

Sorry that I am in NeurIPS and I cannot access my working computer in lab now. I will email you the checkpoints and log files after I returning Shanghai. Feel free to remind me if I forget this.

**Comment by RayYoh** [comment]
Thanks for your prompt reply. Since I have not downloaded Structure3D and processed the S3DIS, so I didn't use the config file you mentioned.

I have tested another case. In this case, the feat shape is 
![image](https://github.com/user-attachments/assets/e232e9a7-9111-4b8d-877d-9fc24935edf5)
current_resolution is 292; the grid_index is like:
![image](https://github.com/user-attachments/assets/021e939f-bd37-43ae-850f-fc08d91ad4f0)

**Comment by RayYoh** [comment]
Hi Haoyi @HaoyiZhu ,

I find that many zero values is not a problem. It is caused that some points not fall in those voxels.

**Comment by HaoyiZhu** [comment]
Okay. Sounds good!

**Comment by RayYoh** [comment]
> Actually, I get a very low performance even after 20+ epochs. However, using the same pipeline, PTv3 works well. Yeah, I have sent an email to Xiaoyang but has not get response.
> 
> Additionaly, I tried to run this config [here](https://github.com/OpenGVLab/PonderV2/blob/main/configs/scannet/pretrain-ponder-spunet-v1m1-0-base.py) which use ScanNet solely. The problem I encounter is the grid index exceeds the shape of feat a lot resulting in all zero feats. ![image](https://private-user-images.githubusercontent.com/35106336/395468935-7095e9a0-9b05-4531-910b-d30052c8f1c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQxNzIyMzYsIm5iZiI6MTczNDE3MTkzNiwicGF0aCI6Ii8zNTEwNjMzNi8zOTU0Njg5MzUtNzA5NWU5YTAtOWIwNS00NTMxLTkxMGItZDMwMDUyYzhmMWM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE0VDEwMjUzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlNDhlNGRiNDU5MmU1YjFmZTY3NjlkY2Y3ZjIyYzRjNzU5OTBhZDUwMTc3YmRlNzdlNWJlMzI3NTAwMzk2ZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.x371sEV0sbdtJrsmVH70uskYUL4Ah96hlSCp-rsSDDg) I am wondering have you ever encountered this problem? And is it possible to share the checkpoint or log file of this config? Thanks a lot.

Hi Haoyi. For the worse performance, I also find the problem. Since I used the Pointcept codebase previously and just added PonderV2 in my own code. Previously, I added one line in the Trainer for grid clip, like this:
![image](https://github.com/user-attachments/assets/bee719c5-921d-43fc-9f31-fc69ab3f8b48)
When I comment out this line, everything goes well. It influences SparseUnet a lot but not PTv3. Sorry for that.
But I still hope you can share the checkpoint that just pre-trained on ScanNetV2 for comparison. You know, using all datasets, and PPT is a little bit time-consuming. Thanks again!

**Comment by HaoyiZhu** [comment]
Hi, I have sent the checkpoints to your email, please check it out! Welcome any follow-up discussions!

**Comment by RayYoh** [comment]
Thanks a lot.
