### ISSUE TITLE
Looking forward to seeing more instructions and code

### ISSUE THREAD

**Issue by WeijianZhang123** [OpenGVLab/PonderV2#3]
Hi, thanks for your great work. :thumbsup:
Looking forward to seeing more instructions and code! :smiley:

**Comment by HaoyiZhu** [comment]
Thanks! We will add more and more instructions as well as codes / checkpoints in the late of this month.

**Comment by HaoyiZhu** [comment]
Hi, we have released more detailed instructions, multi-dataset trianing and models now! Please check out @WeijianZhang123 . More configs and pretrained weights will be available soon.

**Comment by WeijianZhang123** [comment]
Thanks!
