### ISSUE TITLE
How can I run the downsteam tasks with your model?

### ISSUE THREAD

**Issue by elenacliu** [OpenGVLab/PonderV2#4]
How can I run the downsteam tasks with your model? Will you provide some example code snippets?

**Comment by HaoyiZhu** [comment]
Thanks! We will add more and more instructions as well as codes / checkpoints in the late of this month.

**Comment by HaoyiZhu** [comment]
Hi, we have added more instructions now! @elenacliu More configs as well as pre-trained checkpoints will be available soon.
