### ISSUE TITLE
 how to use the network for semantic segmentation? 

### ISSUE THREAD

**Issue by mostafa501** [OpenGVLab/PonderV2#7]
Hi, thank you for publishing this great work. I have a question related to testing my collected point clouds. I need to test my own collected data for semantic segmentation using a pretrained model (checkpoint file) that used without making full training to S3DIS datasets, is this available ? how to use it?
Thank you for your interset and reply.

**Comment by HaoyiZhu** [comment]
Hi, thanks for you intersting! You can download our pretrained checkpoints in [docs/model_zoo.md](docs/model_zoo.md)
