### ISSUE TITLE
Change method for rendering decoder

### ISSUE THREAD

**Issue by BoynextDoor114514** [OpenGVLab/PonderV2#8]
Hello!
I'm now trying to test different rendering methods for rendering decoder, but I have no idea which part in this repo should I pay attention to. Could you please give me some suggestions?

**Comment by HaoyiZhu** [comment]
Hi, thanks for you interest! You can consider modify [render_utils](https://github.com/OpenGVLab/PonderV2/tree/main/ponder/models/ponder/render_utils). We modified this part from [SDFStudio](https://github.com/autonomousvision/sdfstudio).
